Added first two conventions on the guidelines
inaka/rest_guidelines pull request #4
Opened 2017-03-08 13:26 UTC by agerace

Before merging this PR, go over this checklist:
- [ ] The issue was approved by a considerable number of votes
- [ ] The rule text respects the structure:
    - [ ] Title
    - [ ] Short Description
    - [ ] Examples
    - [ ] Reasoning

2017-03-08 13:51 UTC, volbap requested changes
Great! Good start. Just a couple of little fixes are needed.

2017-03-08 13:51 UTC, volbap commented on README.md
> +Even though in some programming languages is common to name variables or object instances with camelCase names, we consider the snake_case is the most readable and understandable way to named the key
(...) we consider the snake_case is the most readable and understandable way to **name** the key fields on a JSON response

2017-03-08 13:51 UTC, volbap commented on README.md
> -#### Maintain existing style
@agerace We do not want to delete this one! :P

2017-03-08 17:58 UTC, agerace commented on README.md
> -#### Maintain existing style
oh, upsi... my bad? jajaja 😅

2017-03-08 17:59 UTC, elbrujohalcon requested changes

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> -#### Maintain existing style
I agree with @volbap

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> +> When the endpoint returns a JSON, the keys should always be in snake_case, unless you have a super edge case.
No unles'es in the guidelines. Exceptions do exist, but the guidelines define the good scenario only.

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> +> When the endpoint returns a JSON, the keys should always be in snake_case, unless you have a super edge case.
That's why they are *guidelines* and not *rules*

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> +Even though in some programming languages is common to name variables or object instances with camelCase names, we consider the snake_case is the most readable and understandable way to named the key
on a JSON response -> on a JSON object

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> +> When the endpoint returns, for example, an array, it should be returned as a plain array, not a dictionary with the array as a value.
dictionary -> object

dictionaries in JSON are just called _objects_

2017-03-08 17:59 UTC, elbrujohalcon commented on README.md
> +If the client expects an array it could ( and would ) be confusing to receive a dictionary with one key containing the array as a value.
This is not the proper reasoning. The reasoning behind this rule is _semantics_.
If you ask `GET /entities`, the natural meaning of that is _**GET** me all the **entities**_ not _**GET** me an object that contains all the **entities** in one of its properties_. There are scenarios when that is desired, but we should always default to the implementation that's most intuitive.

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +Even though in some programming languages is common to name variables or object instances with camelCase names, we consider the snake_case is the most readable and understandable way to named the key
I found 3 misspelled words in this sentence: 
- JSON
	- *Suggested Replacements:* son, jason, jeon
- snake_case
- camelCase

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ##### Reasoning
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ## Conventions & Rules
I found 2 misspelled words in this sentence: 
- &
	- *Suggested Replacements:* , k, p, u, e, z, j, &c, o, t, d, y, i, n, s, c, x, h, m, r, b, w, g, l, q, a, v, f
- ##

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +#### Use snake_case with JSON
I found 3 misspelled words in this sentence: 
- JSON
	- *Suggested Replacements:* son, jason, jeon
- snake_case
- ####

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +> When the endpoint returns a JSON, the keys should always be in snake_case, unless you have a super edge case.
I found 3 misspelled words in this sentence: 
- snake_case
- JSON
	- *Suggested Replacements:* son, jason, jeon
- >
	- *Suggested Replacements:* , k, p, u, e, z, j, o, t, d, y, i, n, s, c, x, h, m, r, b, w, g, l, q, a, v, f

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +> When the endpoint returns a JSON, the keys should always be in snake_case, unless you have a super edge case.
I found 3 misspelled words in this sentence: 
- snake_case
- JSON
	- *Suggested Replacements:* son, jason, jeon
- >
	- *Suggested Replacements:* , k, p, u, e, z, j, o, t, d, y, i, n, s, c, x, h, m, r, b, w, g, l, q, a, v, f

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +##### Reasoning
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +##### Examples
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ***
I found 1 misspelled word in this sentence: 
- ***

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ###### Good
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ***
I found 1 misspelled word in this sentence: 
- ***

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +##### Examples
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +###### Good
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +Even though in some programming languages is common to name variables or object instances with camelCase names, we consider the snake_case is the most readable and understandable way to named the key
I found 3 misspelled words in this sentence: 
- JSON
	- *Suggested Replacements:* son, jason, jeon
- snake_case
- camelCase

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +###### Bad
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +##### Reasoning
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +#### Don't use response envelopes by default
I found 1 misspelled word in this sentence: 
- ####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ##### Reasoning
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ###### Good
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +###### Good
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ## Conventions & Rules
I found 2 misspelled words in this sentence: 
- &
	- *Suggested Replacements:* , k, p, u, e, z, j, &c, o, t, d, y, i, n, s, c, x, h, m, r, b, w, g, l, q, a, v, f
- ##

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ##### Examples
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ###### Bad
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +#### Use snake_case with JSON
I found 3 misspelled words in this sentence: 
- JSON
	- *Suggested Replacements:* son, jason, jeon
- snake_case
- ####

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ###### Bad
I found 1 misspelled word in this sentence: 
- ######

2017-03-08 18:03 UTC, sheldonci commented on README.md
>  ##### Examples
I found 1 misspelled word in this sentence: 
- #####

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +> When the endpoint returns, for example, an array, it should be returned as a plain array, not a dictionary with the array as a value.
I found 1 misspelled word in this sentence: 
- >
	- *Suggested Replacements:* , k, p, u, e, z, j, o, t, d, y, i, n, s, c, x, h, m, r, b, w, g, l, q, a, v, f

2017-03-08 18:03 UTC, sheldonci commented on README.md
> +#### Don't use response envelopes by default
I found 1 misspelled word in this sentence: 
- ####

2017-03-08 18:04 UTC, sheldonci commented on README.md
> +###### Bad
I found 1 misspelled word in this sentence: 
- ######

2017-03-09 17:32 UTC, elbrujohalcon requested changes

2017-03-09 17:32 UTC, elbrujohalcon commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
HA HA! Very funny… not sure if that's the spirit we want to showcase in this repos. @volbap what do you think?

2017-03-09 17:32 UTC, elbrujohalcon commented on README.md
> +> Use all the HTTP verbs. If you have to Create something use POST. If you want to Eead Something. if you want to Update something use PATCH or PUT. If you want to Delete something use DELETE. Always
Eead ?

2017-03-09 17:32 UTC, elbrujohalcon commented on README.md
> +Using the right HTTP Verb on each resource will make clearer what the resource is made for and what we should expect it to do, receive and return. Using always GET is like using your spoon to eat you
Add something about how you can _read_ or _write_ your intentions, e.g.:

* **PUT** /entities/1 : it puts the entity #1 in the server
* **GET** /update_entity?id=1&title=t : it gets all the update_entities with id = 1 and title = t … WAT?

2017-03-09 17:33 UTC, agerace commented on README.md
> +> Use all the HTTP verbs. If you have to Create something use POST. If you want to Eead Something. if you want to Update something use PATCH or PUT. If you want to Delete something use DELETE. Always
Read jajaja

2017-03-09 17:34 UTC, agerace commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
jajaja yeah,  I was thinking the same when I write but I jumped into the pool :P

2017-03-09 17:36 UTC, volbap commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
Hahahaha 🤣  Although it made me laugh out loud, we should **not** include these kind of comments in our guidelines. Sorry, @agerace , but I encourage removing it.

2017-03-09 17:36 UTC, volbap commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
Maybe you could keep them in mind for whenever you write a related blogpost ;)

2017-03-09 17:38 UTC, volbap submitted a review, later dismissed

2017-03-09 17:38 UTC, volbap commented on README.md
> +#### Use all HTTP verbs ( Not everything is a GET )
Are these spaces after and before the parenthesis on purpose? I would suggest removing them, and writing them the normal way: `Use all HTTP verbs (Not everything is a GET)`
Thoughts @elbrujohalcon ?

2017-03-09 17:40 UTC, elbrujohalcon commented on README.md
> +> Use all the HTTP verbs. If you have to Create something use POST. If you want to Eead Something. if you want to Update something use PATCH or PUT. If you want to Delete something use DELETE. Always
Then . and , are wrong… I bet you wanted to say:
> Use all the HTTP verbs. If you have to Create something use POST. If you want to Read something use GET. If you want to Update something use PATCH or PUT. If you want to Delete something use DELETE. Always remember C.R.U.D. (Create, Read, Update, Delete) when setting the verb for your resource.

2017-03-09 18:16 UTC, agerace commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
@volbap  ?

2017-03-09 18:16 UTC, agerace commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. Think about it as a christmas gift. If you ask santa for all the
roger that

2017-03-09 18:20 UTC, agerace commented on README.md
> +> Use all the HTTP verbs. If you have to Create something use POST. If you want to Eead Something. if you want to Update something use PATCH or PUT. If you want to Delete something use DELETE. Always
ups, yes, I forgot the "use GET" there.

2017-03-09 18:44 UTC, elbrujohalcon requested changes

2017-03-09 18:44 UTC, elbrujohalcon commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for entities, not an object with the entities inside one of its properties. So don't envelope things that should be being retrieved directly
...you are asking for a list of entities, not... ....things that should be retrieved directly.

2017-03-09 20:15 UTC, elbrujohalcon requested changes
Last round of comments, I promise

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +    [
You should add backticks around the code here, something like
```js
this
```

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +    { "items" : [
You should add backticks around the code here, something like
```js
this
```

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +> When the endpoint returns a JSON, the keys should always be in snake_case.
This should also apply to JSONS in the request, not just the response

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +      {
You should add backticks around the code here, something like
```js
this
```

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +      {
You should add backticks around the code here, something like
```js
this
```

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
> +If you're calling a **GET** on `/entities` , you're asking for a list of entities, not an object with the entities inside one of its properties. So don't envelope things that should be retrieved dire
extra space before ,

2017-03-09 20:15 UTC, elbrujohalcon commented on README.md
>  #### Maintain existing style
I would like this to be the first guideline in the list, if possible

2017-03-09 20:38 UTC, agerace commented on README.md
>  #### Maintain existing style
everything it's possible if you believe hard enough @elbrujohalcon !

2017-03-09 20:50 UTC, elbrujohalcon requested changes

2017-03-09 20:50 UTC, elbrujohalcon commented on README.md
> +	"caption": "string",
indentation is broken here

2017-03-09 20:55 UTC, elbrujohalcon approved these changes

2017-03-09 20:55 UTC, merged